name: produtos_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Utils
  intl: ^0.19.0
  dio: ^5.8.0
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
